### PR TITLE
fix: Add missing href to toc.yml

### PR DESCRIPTION
**Pull request by lukeblevins**
GitHub Issue (If applicable): N/A

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [ ] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable): N/A

### CODE REVIEW

**Review by nickrandolph — CHANGES_REQUESTED** [review]
I think there are other docs that need to be enabled - check out the other docs and enabled them in the toc if they're complete enough to publish

**Comment by lukeblevins** [comment]
@nickrandolph Are there additional pages that meet our standards for quality?

Maybe I'm mistaken, but that appeared to cover everything that isn't a stub. Definitely open to your input though 👍🏻

**Comment by nickrandolph** [comment]
@lukeblevins I think this one can be added: https://github.com/unoplatform/uno.extensions/blob/main/doc/Learn/Tutorials/Authentication/HowTo-Authentication.md

Otherwise, yeh, the rest need to have some words around the sample code before we can push them

**Comment by lukeblevins** [comment]
@nickrandolph Should I close this PR?

**Review by jeromelaban — APPROVED** [review]

**Review by agneszitte-nventive — APPROVED** [review]

**Comment by agneszitte-nventive** [comment]
> @nickrandolph Should I close this PR?

@lukeblevins, @nickrandolph maybe this PR can be updated?

**Comment by lukeblevins** [comment]
@agneszitte-nventive On it now.

**Pull request closed without merging**
