### PR TITLE
feat: [MVUX] Improve nullable support

### PR DESCRIPTION
**Pull request by dr1rrb**
closes https://github.com/unoplatform/uno.extensions/issues/1605

## Feature
Improve nullable support in feed factories and relevant operators

## What is the current behavior?
Nullable annotation are not used to interpreted by the feeds. There is no recommendation to use non nullable types in feeds and users are often involuntary using using `Some(null)` while they should use (/ thinking they are using) `None`.

## What is the new behavior?
* Most common factory methods (`<Feed|State>.Async[Enumerable]`) are now constrained with `T : notnull`
* `Select` and `SelectAsync` operators are also constrained with `TResult : notnull`
* When user returns a `T`  with the `T : struct` constraint, we allowed him to return a `T?` which is interpreted as `None`
* In any time, when user provide a `T` that is ref type and `null`, it's interpreted as `None` (e.g. `Feed<MyObject>.Async(async _ => null!)` will now goes in `None`).
* `SelectData` and `SelectDataAsync` operators has been added to allow user to still use `Some(null)` if needed.

## PR Checklist
- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md). (for bug fixes / features) 
- [x] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [ ] ~~Contains **NO** breaking changes~~
- [ ] Updated the [Release Notes](https://github.com/unoplatform/uno/tree/master/doc/ReleaseNotes)
- [x] Associated with an issue (GitHub or internal)

## Other information
# COMPILATION BREAKING CHANGES
This PR introduces few compilation breaking changes. Here is a shot summary of the known breaking 
* `Feed.Async(async _ => default(MyObject))` is no longer allowed, to fix you need to specify the type of the value of the feed, i.e. use `Feed**<MyObject?>**.Async(async _ => default(MyObject))`. Same for `Feed.AsyncEnumerable`, `State.Async` and `State.AsyncEnumerable`
* `myFeed.Select(_ => default(MyObject))` is no longer allowed, to fix you need to use the `SelectData` operator. Same for `SelectAsync` where you need use `SelectDataAsync`.

# BEHAVIOR BREAKING CHANGES
This PR also introduces few behavior changes that could be breaking in few use case. Those are describe in the issue https://github.com/unoplatform/uno.extensions/issues/1605, and which can be summarized "any time you return a `null` value, it's now automatically converted as `None`". This was already the case for some factories and operators and is expected to cause issue only in really rare use-cases. If you are encountering such an issue, use factories and operators overload that accepts `Option<T>` instead of `T`.

### CODE REVIEW

**Comment by nickrandolph** [comment]
@dr1rrb how are we going to deal with the breaking changes. I assume we need to push to v4 of extensions, to reflect breaking changes?

**Comment by dr1rrb** [comment]
> @dr1rrb how are we going to deal with the breaking changes. I assume we need to push to v4 of extensions, to reflect breaking changes?

I would agree, but usually (unfortunately) the "major" version number is more often a "marketing number" than a "semantic number"... especially since we have released v3 quite recently. We will have to discuss about that ...

**Pull request merged**
