### PR TITLE
Made 'WebAuthenticatorBrowser' public to reuse it (in our case for Firebase authentication)

### PR DESCRIPTION
**Pull request by dim-37**
GitHub Issue (If applicable): #1887

## PR Type

What kind of change does this PR introduce?

- Refactoring (no functional changes, no api changes)
Changed access specifiers for classes WebAuthenticatorBrowser, OidcAuthenticationProvider, OidcAuthenticationSettings from internal to public 

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [X] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [X] Associated with an issue (GitHub or internal)

### CODE REVIEW

**Review by xperiandri — APPROVED** [review]

**Comment by xperiandri** [comment]
@nickrandolph

**Comment by nickrandolph** [comment]
Did you need all the providers to be public as well as the browser class?
The providers are intentionally internal as the implementation is likely to change and don't want to expose it unless you see it as important

**Comment by dim-37** [comment]
I just didn't want to change the fact that the WebAuthenticatorBrowser class is inside the OidcAuthenticationProvider I can now go back and just move the WebAuthenticatorBrowser outside.

**Review by nickrandolph — APPROVED** [review]

**Comment by xperiandri** [comment]
@nickrandolph how to trigger conentional commits validation?

**Pull request merged**
